Add jq filter
thp/urlwatch pull request #626
Opened 2021-03-03 00:23 UTC by robgmills

Adds the ability to select content from JSON data using `jq` - a lightweight JSON processor - filter syntax.  The `jq` filters are similar to CSS or XPath selectors, with added operators to transform the data.

Addresses #592 in a different way.

2021-03-03 00:28 UTC, robgmills commented
Thanks for sharing this project with us!  I'm not super well-versed in Python projects and this has been a good experience.

I can see in the Travis job how to run tests and that I have some syntax issues in the documentation.  I'll add a test or tests for this filter - is there anything in particular you want me to test for?  I'll also clean up the documentation syntax issues I introduced.

2021-03-03 04:09 UTC, robgmills commented
These documentation driven tests are pretty cool!  I'll have to use them as inspiration later.

Sorry for the disjointed commits - I normally try to keep things cleaner.  This was a good learning experience!  I'm excited to hear your thoughts!

2021-04-05 07:36 UTC, thp commented on lib/urlwatch/filters.py
> +        return jq.text(subfilter['query'], json.loads(data))
One "optimization" here could be to store the result of `json.loads(data)` in line 878, and re-use the result in line 888 to not have to re-parse the JSON data.

2021-04-05 07:36 UTC, thp requested changes
Nice and clean. One comment about avoiding double-parsing of JSON. Also, you could add this change to `CHANGELOG.md`.

2021-04-06 03:27 UTC, robgmills commented
Thanks for the feedback @thp!

2021-04-09 11:48 UTC, thp approved these changes

2021-04-09 11:49 UTC, merged

2021-04-09 11:49 UTC, thp commented
Merged, thanks!

2021-04-19 21:00 UTC, smithl commented
Appreciate this addition very much, nice work!