reporters: test report jobs separately
thp/urlwatch pull request #772
Opened 2023-10-24 14:52 UTC by marunjar

This PR should make the `--test-reporter` option respect `separate` flag too.
It's just applying the changes already made with #721 from `submit_all` method to the `submit_one` method as well.

fixes #771

I hope this is ok so far, because my python is not the best :wink:

2023-10-24 18:41 UTC, thp requested changes
Looks good. Please update `CHANGELOG.md`, describing your changes.

2023-10-25 08:24 UTC, marunjar commented
> Looks good. Please update `CHANGELOG.md`, describing your changes.

done

2023-10-25 21:03 UTC, thp approved these changes

2023-10-25 21:05 UTC, merged

2023-10-25 21:05 UTC, thp commented
Merged, thanks!