Add option to disable individual jobs
thp/urlwatch pull request #785
Opened 2024-01-17 13:32 UTC by Jamstah

This adds an `enabled` flag for all jobs that allows a user to disable individual jobs without having to comment out lots of lines of yaml.

Fixes #625

2024-01-23 19:53 UTC, thp requested changes
Very nice and complete PR, thanks!

Two commends + please update `CHANGELOG.md` with the additional feature.

2024-01-23 19:53 UTC, thp commented on docs/source/jobs.rst
> +- ``enabled``: Can be set to false to disable an individual job (default is true)
```suggestion
- ``enabled``: Can be set to false to disable an individual job (default is ``true``)
```

2024-01-23 19:53 UTC, thp commented on lib/urlwatch/jobs.py
> +        return self.enabled == None or self.enabled
```suggestion
        return self.enabled is None or self.enabled
```

2024-01-23 23:19 UTC, Jamstah commented
Done, thanks for the review.

2024-01-24 23:08 UTC, Jamstah commented
Should I also be regenerating the man pages, or does that get done at release time?

2024-02-12 18:11 UTC, thp approved these changes

2024-02-12 18:17 UTC, merged

2024-02-12 18:17 UTC, thp commented
Thanks!